import { WATER_MASK } from "./waterMask";

// Shared water check (browser + API route). Looks a point up in the packed
// ~110m-cell bitmask generated by scripts/generate-water-mask.mjs. Cells are
// marked water only when solidly water, so shoreline buildings stay pickable.

let bits: Uint8Array | null = null;

function mask(): Uint8Array {
  if (!bits) {
    if (typeof Buffer !== "undefined") {
      bits = new Uint8Array(Buffer.from(WATER_MASK.data, "base64"));
    } else {
      const bin = atob(WATER_MASK.data);
      bits = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bits[i] = bin.charCodeAt(i);
    }
  }
  return bits;
}

/** True when the point sits in open water (sea, creek, lake) in the MMR. */
export function isWaterPoint(lat: number, lng: number): boolean {
  const { zoom, x0, y0, scale, width, height } = WATER_MASK;
  const n = 2 ** zoom;
  const px = (((lng + 180) / 360) * n - x0) * 256;
  const mercY = (1 - Math.asinh(Math.tan((lat * Math.PI) / 180)) / Math.PI) / 2;
  const py = (mercY * n - y0) * 256;
  const col = Math.floor(px / scale);
  const row = Math.floor(py / scale);
  if (col < 0 || row < 0 || col >= width || row >= height) return false;
  const idx = row * width + col;
  return (mask()[idx >> 3] & (1 << (idx & 7))) !== 0;
}
